In [1]:
import torch
import torch.nn as nn

In [47]:
N = 4  # batch size
C = 3  # number of classes

In [48]:
targets = torch.randint(0, C, (N,), dtype=torch.long)
print(targets)
targets.shape

tensor([2, 2, 0, 0])


torch.Size([4])

In [49]:
logits = torch.randn(N, C, requires_grad=False)*2.
print(logits)
logits.shape

tensor([[-2.5859, -4.2235,  2.9367],
        [ 0.1978, -0.5029, -0.6672],
        [ 0.3942, -1.7594,  2.5173],
        [-1.8925,  3.7303,  0.0526]])


torch.Size([4, 3])

In [50]:
loss_fn = nn.CrossEntropyLoss(reduction='none')
loss = loss_fn(logits, targets)
print(loss)
loss.shape

tensor([4.7611e-03, 1.5159e+00, 2.2484e+00, 5.6513e+00])


torch.Size([4])

In [51]:
probabilities = nn.Softmax(dim=-1)(logits)
print(probabilities)

tensor([[3.9766e-03, 7.7321e-04, 9.9525e-01],
        [5.2156e-01, 2.5883e-01, 2.1961e-01],
        [1.0557e-01, 1.2252e-02, 8.8218e-01],
        [3.5130e-03, 9.7192e-01, 2.4571e-02]])


In [52]:
for i in range(4):
    print(-torch.log(probabilities[i][targets[i]]))

tensor(0.0048)
tensor(1.5159)
tensor(2.2484)
tensor(5.6513)
